#!/usr/bin/env bash
 
if [[ -z "$1" ]] ; then
    echo "USAGE: $0 DIR" 1>&2
    exit 1
fi
dir=${1}

echo "Do you want to unlock the contents of ${dir}?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) find ${1} -type f -name "*.grib2" -print0 | xargs --null chmod u+w; break;;
        No ) exit;;
    esac
done

